name: Publish Docker image 

on:
  push:
    branches: ['main']

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/setup-node@v4
      with:
           node-version: 20
        
    - name: Check out the repo
      uses: actions/checkout@v4
    - uses: actions/setup-python@v3
      with:
       python-version: 3.8.2
      
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9 
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

              
    - name: Get latest tag
      id: tag
      uses: demy06031978/nodejs-app:latest@main
      with:
       cmd: yq '.modules[].sources[] | select(.url == "*/foo.git").tag' main.yml
       
   
      
    - name: Show latest tag
      run: |
       echo '${{ steps.tag.outputs.value }}'   
          
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
          images: demy06031978/nodejs-app  
   
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}   

    - id: pass-report-into-summary
      name: Pass Report into the Summary
      run: |
           {
            echo "### My Report Header"
            echo "\`\`\`"
            cat ${{ env.report_filename }}
            echo ""
            echo "\`\`\`"
            } >> $GITHUB_STEP_SUMMARY
       

        
        
